# #cloud-config
# package_update: true
# packages:
#   - apt-transport-https
#   - ca-certificates
#   - curl
#   - software-properties-common
# runcmd:
#   - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#   - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#   - apt-get update
#   - apt-get install -y docker-ce
#   - usermod -aG docker ${admin_username}
#   - systemctl enable docker
#   - systemctl start docker
